ARG BASE_REGISTRY=cloudshegerlab.jfrog.io
ARG BASE_IMAGE=ubi/ubi9/python-39
ARG BASE_TAG=3.9
#cloudshegerlab.jfrog.io/ubi/ubi9/python-39:3.9
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

USER 0

##pip install --no-index /path/to/pip_file
